// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
function monitor(inputEle, guid) {
	// monitor inputEle dom changes
	MutationObserver.observe(inputEle, {
		attributes: true,
		attributeFilter: ["value"],
		attributeOldValue: true,
		attributeFilter: ["value"],
		attributeOldValue: true
	}, function (mutations) {
		if (mutations) {
			// mx.data.saveDocument(guid, 'file name', null, inputEle.files[0]);
			console.log("save document", guid, 'file name', null, inputEle.files[0]);
		}
	});
}
// END EXTRA CODE

/**
 * @param {MxObject} fileToUpload
 * @returns {Promise.<void>}
 */
export async function JavaScript_action(fileToUpload) {
	// BEGIN USER CODE
	const guid = fileToUpload.getGuid();
	const containerEle = document.querySelector('.id-' + fileToUpload.get('_id').toNumber());
	if (containerEle) {
		const inputEle = containerEle.querySelector('.mx-fileinput .sr-only input');
	
		monitor(inputEle, guid);
	}
	// END USER CODE
}
